### ISSUE TITLE
Remove all unnecessary ruby packages

### ISSUE THREAD

**Issue by voxik** [minimization/content-resolver-input#167]
It would be nice if all ruby package, except those listed in 

* `sst_cs_apps-ruby-db-connectors.yaml`
* `sst_cs_apps-ruby-rspec.yaml`
* `sst_cs_apps-ruby.yaml`

are removed. There is not even clear why they are included (probably via transitive dependencies, but hard to tell from the [app](https://tiny.distro.builders/view-reasons--view-eln--x86_64.html)

**Comment by asamalik** [comment]
That view shows you what workloads pulled them in. If you click on any of the workload, it gets you to its detail, and there is another "Reasons of presence" tab that's package level.

**Comment by voxik** [comment]
If I enter "rubygem" into the filter, there are just expected packages. However, if I go into Buildroot tab, there is many more rubygem- packages without explanation.

**Comment by voxik** [comment]
Just FTR, I don't want to mark these as "unwanted", because if they were necessary, they'd be perfectly fine, but they are included for no apparent reason. And if there is reason due to dependencies, the dependency chains should be cut on the right place.
