### ISSUE TITLE
ruby 2.6 module builds ruby 2.7

### ISSUE THREAD

**Issue by voxik** [minimization/content-resolver-input#23]
Here is some definition of Ruby 2.6 module:

https://github.com/minimization/content-resolver-input/blob/master/configs/rhel-8-appstream-module-
ruby-2.6.yaml#L8

but it seems it builds Ruby 2.7:

https://tiny.distro.builders/workload--rhel-8-appstream-module-ruby-2.6--fedora-empty-base--repository-fedora-eln--x86_64.html

**Comment by asamalik** [comment]
Yeah, that config shouldn't have existed, or be titled differently.

At this moment, Content Resolver doesn't support specific modules on the input, in only consumes standard packages or packages from default module streams. Although module support is coming very shortly.

@contyk Is it one of the configs you've generated back then? There are probably more of those. I think we should either remove all of these, as they don't represent what they look like, or rename them to something else. Any preference? Do you still have the scripts for the potential renaming? Do all of these modules even exist in Fedora?

**Comment by asamalik** [comment]
@voxik Do you have a Ruby 2.6 module in Fedora you want included in ELN?

* If not, free to just delete any entries owned by "bakery" — they'll get removed in the end anyway.
* If you do, please wait for the module support that's coming shortly.

Or if you want to include Ruby in whatever version is now in Fedora, feel free to rename and modify this file so it reflects your plans with Ruby.

**Comment by voxik** [comment]
That is not that easy I am afraid. It would probably make sense to include the latest Ruby module as they comes into Fedora. That means it should be Ruby 2.6 ATM, but since Ruby 2.7 is in the works, it should be changed as soon as it lands.

If you think about master, then that is not solution, since master is quite meaningless for modularity.

**Comment by asamalik** [comment]
Module support added!

See the [workload config spec](https://github.com/minimization/content-resolver/blob/master/config_specs/workload.yaml#L84).
