### ISSUE TITLE
Provide "refresh" date of the content resolver output

### ISSUE THREAD

**Issue by voxik** [minimization/content-resolver-input#356]
Yesterday, I have [updated](https://src.fedoraproject.org/rpms/rubygem-rack/c/e5f553ede9d0fefc8bb14e158401ddf9b0a5c72f?branch=master) rubygem-rack to drop the rubygem-thin dependency. However, today, the rubygem-thin is still listed as being part of buildroot:

https://tiny.distro.builders/view-buildroot--view-eln--x86_64.html
https://tiny.distro.builders/view-rpm--view-eln--rubygem-thin.html

Providing the "refresh" date would help understand, if there was already chance the change was propagate already or not.

**Comment by asamalik** [comment]
Easy enough to do, adding to my list!

**Comment by voxik** [comment]
Just FTR, these are the issues why I'd like to have the "refresh date".

Looking at [rubygem-rspec2](https://tiny.distro.builders/view-rpm--view-eln--rubygem-rspec2.html), it is required by [rubygem-RedCloth](https://tiny.distro.builders/view-rpm--view-eln--rubygem-RedCloth.html). But I have removed the dependency [a while ago](https://src.fedoraproject.org/rpms/rubygem-RedCloth/c/e7772b1b407e8356b248ee070dfd7fb063b1862c?branch=master) and there is certainly [ELN build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1631487). So if there was refresh date, I'd understand that the information is probably not up2date.

**Comment by asamalik** [comment]
Did this yesterday, see it live on any page!

**Comment by voxik** [comment]
I can confirm that the rubygem-RedCloth display the date, thx!

But am I impatient if I don't see it on the [rubygem-rspec2](https://tiny.distro.builders/view-rpm--view-eln--rubygem-rspec2.html) page? Or was this page not refreshed, because rubygem-rspec2 was dropped from the content set after the changes?

**Comment by voxik** [comment]
I can't see rubygem-rspec2 [here](https://tiny.distro.builders/view-buildroot--view-eln--x86_64.html), so the later is probably the reason. Should I report it separately?
