### ISSUE TITLE
Include rubygem-ronn-ng instead of rubygem-ronn which was retired

### ISSUE THREAD

**Issue by voxik** [minimization/content-resolver-input#387]
I wonder how often the dependencies are updated, because rubygem-ronn replaced in Fedora Rawhide by rubygem-ronn-ng, but this was not reflected anywhere and I wonder why?

**Comment by asamalik** [comment]
It runs every ~90 mins, using the latest ELN compose. If you get to the RPM details page (click on its name in one of the lists) you'll see the full NEVRA that was used.

**Comment by asamalik** [comment]
Oh, it's a buildroot package. That takes a little longer, it's done by an external service, because it needs to rebuild some SRPMs for all architectures before resolving them, and that's beyond what Content Resolver does. But it shouldn't take this long. Did it get to the ELN compose?

**Comment by voxik** [comment]
I think that [ronn-ng](https://tiny.distro.builders/view-rpm--view-eln--rubygem-ronn-ng.html) got into the content resolver. But if there was more transparency, when one could expect such changes, that would be nice.

Also, si the [ronn page](https://tiny.distro.builders/view-rpm--view-eln--rubygem-ronn.html) kept around on purpose?

**Comment by voxik** [comment]
This is probably resolved
