### ISSUE TITLE
Outdated content

### ISSUE THREAD

**Issue by voxik** [minimization/content-resolver-input#588]
It seems that the content resolver content is not refreshed for a few weeks:

Compose Date: 2021-05-12 (2 days ago)
Page refreshed at 14 May 2021 15:48 UTC. 

checking at:

https://tiny.distro.builders/view-srpm--view-eln--rubygem-tilt.html
https://tiny.distro.builders/view--view-eln.html

**Comment by asamalik** [comment]
There was an issue with the builder, I fixed that yesterday. Thanks for reporting!
