### ISSUE TITLE
Content resolver input is not updated

### ISSUE THREAD

**Issue by voxik** [minimization/content-resolver-input#589]
Looking at [rubygem-kramdown-parser-gfm](https://tiny.distro.builders/view-srpm--view-eln--rubygem-kramdown-parser-gfm.html), it shows 15 days old content. Can we have the data refreshed?

**Comment by asamalik** [comment]
That's the ELN compose being old, it's not a Content Resolver issue.

**Comment by voxik** [comment]
Ah, right :man_facepalming: Is this know issue? Is it reported somewhere?

**Comment by asamalik** [comment]
No worries! ELN lives here: https://github.com/fedora-eln/eln
