### ISSUE TITLE
libradosstriper is "unwanted" but still in comps

### ISSUE THREAD

**Issue by ktdreyer** [minimization/content-resolver-input#623]
libradosstriper-devel and libradosstriper1 are in the RHEL 9 CRB repository.

These are already listed in `content-resolver-input/configs/sst_rh_samba_storage-unwanted.yaml`. Should I submit a comps XML change directly to https://gitlab.com/redhat/centos-stream/release-engineering/comps/-/blob/main/comps-centos-stream-9.xml.in ?

**Comment by jwboyer** [comment]
Please.  The compose contents are not directly tied to CR itself.

**Comment by ktdreyer** [comment]
Thanks. I opened https://gitlab.com/redhat/centos-stream/release-engineering/comps/-/merge_requests/88 for this.
