### ISSUE TITLE
Get back the history!

### ISSUE THREAD

**Issue by voxik** [minimization/content-resolver-input#737]
7db4312ac072158521b4d0a67755723fcd43b71e

This ^^ is shocking! Really? There is a lot of business value in the history. It is the source of information why we included or excluded something and it has been dropped just with snap of the finger due to "significantly speed up cloning of this repo." I really can't believe this.

**Comment by asamalik** [comment]
All the history has been archived in the [archive repo](https://github.com/minimization/content-resolver-input-archive). Try cloning it to see how insanely long it takes.

**Comment by voxik** [comment]
Here is the result:

~~~
$ time git clone https://github.com/minimization/content-resolver-input-archive.git
Cloning into 'content-resolver-input-archive'...
remote: Enumerating objects: 19286, done.
remote: Counting objects: 100% (6465/6465), done.
remote: Compressing objects: 100% (2155/2155), done.
remote: Total 19286 (delta 4402), reused 6041 (delta 4303), pack-reused 12821
Receiving objects: 100% (19286/19286), 393.77 MiB | 12.44 MiB/s, done.
Resolving deltas: 100% (13801/13801), done.

real	2m15,856s
user	5m37,717s
sys	0m42,862s
~~~

IOW it took a bit over 2 minutes. This is not fast, but also not terribly slow, given that I typically do this operation once.

If you are for some reasons really concerned about checkout speed, then you could use either:

~~~
$ time git clone https://github.com/minimization/content-resolver-input-archive.git --sparse 
Cloning into 'content-resolver-input-archive'...
remote: Enumerating objects: 19286, done.
remote: Counting objects: 100% (6465/6465), done.
remote: Compressing objects: 100% (2155/2155), done.
remote: Total 19286 (delta 4402), reused 6041 (delta 4303), pack-reused 12821
Receiving objects: 100% (19286/19286), 393.77 MiB | 21.36 MiB/s, done.
Resolving deltas: 100% (13801/13801), done.

real	2m0,393s
user	5m39,012s
sys	0m41,396s
~~~

or even

~~~
 time git clone https://github.com/minimization/content-resolver-input-archive.git --shallow-since=2022-01-01
Cloning into 'content-resolver-input-archive'...
remote: Enumerating objects: 556, done.
remote: Counting objects: 100% (556/556), done.
remote: Compressing objects: 100% (471/471), done.
remote: Total 556 (delta 127), reused 228 (delta 84), pack-reused 0
Receiving objects: 100% (556/556), 165.65 KiB | 3.45 MiB/s, done.
Resolving deltas: 100% (127/127), done.

real	0m0,860s
user	0m0,064s
sys	0m0,053s
~~~

But base on this, now I see that you have taken the opportunity to actually break the history with change from master to main. If you did this, then you could have also rewrite the history in a way to remove the "massive buildroot files we no longer use." you are referring in the commit message.

**Comment by asamalik** [comment]
Wow thanks for the analysis. 2 minutes in unacceptable from my point of view, because I expect many people will want to do a change, and those two minutes of wait would make it unnecessarily painful. And there will be much more cases of doing changes than digging in history.

But!

Would you be willing to see what would it look like without those buildroot files? I see no problem adding back the history if its cleaned up like this.

The reason I didn't do it in the first place was that I wanted to preserve the commit hashes etc. But now that we have the archive repo, it's all there. And if it's convenient to be able to see the history in the same repo, having it here, cleaned up, could be nice.

**Comment by keszybz** [comment]
I created a version of the `main` that restores the history. Github does not allow me to open a pull request, so please see
https://github.com/keszybz/content-resolver-input/commits/main directly. The idea would be to force-push that branch into `main` of this repo.

**Comment by keszybz** [comment]
```console
$ time git clone https://github.com/keszybz/content-resolver-input/
Cloning into 'content-resolver-input'...
remote: Enumerating objects: 8012, done.
remote: Counting objects: 100% (4272/4272), done.
remote: Compressing objects: 100% (1902/1902), done.
remote: Total 8012 (delta 2409), reused 4225 (delta 2370), pack-reused 3740
Receiving objects: 100% (8012/8012), 1.56 MiB | 897.00 KiB/s, done.
Resolving deltas: 100% (5294/5294), done.
git clone https://github.com/keszybz/content-resolver-input/  0.64s user 0.19s system 27% cpu 3.037 total
```

**Comment by asamalik** [comment]
@keszybz wow nice!

**Comment by asamalik** [comment]
This is now done. Thanks a lot!
