### ISSUE TITLE
python-sphinx is unwanted but we maintain it willingly in CRB

### ISSUE THREAD

**Issue by hroncok** [minimization/content-resolver-input#753]
I've noticed on https://tiny.distro.builders/view-srpm--view-eln--python-sphinx.html that this package is marked as unwanted because it is in "Unwanted SELinux packages".

Yet we (cs_apps python-maint) maintain this package willingly and deliberately in CRB (see e.g. https://github.com/minimization/content-resolver-input/pull/399 where it was listed).

What shall be done about this situation?

cc @bachradsusi @torsava

**Comment by jwboyer** [comment]
Add it to your team's listed of wanted packages and drop it from the other teams that have it listed as unwanted.

**Comment by hroncok** [comment]
> Add it to your team's listed of wanted packages 

We cannot do that because there is no known way to define a CRB workload (see https://github.com/minimization/content-resolver-input/pull/399). Adding it to our workload will drag it to AppStream.

> drop it from the other teams that have it listed as unwanted

I can do that.

**Comment by jwboyer** [comment]
> > Add it to your team's listed of wanted packages
> 
> We cannot do that because there is no known way to define a CRB workload (see #399). Adding it to our workload will drag it to AppStream.

@asamalik if CR is going to explicitly define the contents of composes, it needs to understand CRB.

**Comment by asamalik** [comment]
There's still no direct connection between workloads and repos. So you can add it to a workload, it'll show up as required, and then independently on that we can set the repo config.

If you want to make it future-proof, make an entire workload CRB and I'll take care of it when I get to generate the repo config automatically in the near future.

**Comment by hroncok** [comment]
> If you want to make it future-proof, make an entire workload CRB

That is exactly what we had and removed in https://github.com/minimization/content-resolver-input/pull/399 because the packages ended up in AppStream because of that.

**Comment by asamalik** [comment]
Right that's over two years ago. You can go ahead and create CRB workloads now just fine now!
